apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /etc/nginx/nginx.conf
        pathType: Prefix
        backend:
          service:
            name: 
            port:
              number: 80
